### ISSUE TITLE
Decorators

### ISSUE THREAD

**Issue by kristianmandrup** [xpepermint/rawmodeljs#14]
Allow for a @field decorator

'''
@field
name() {
  return {
    // ...
  }
}
'''

**Comment by xpepermint** [comment]
Ref: https://github.com/xpepermint/vue-rawmodel/issues/8
Decorators are coming soon ...

**Comment by kristianmandrup** [comment]
Awesome!!!

**Comment by xpepermint** [comment]
Closing in favor of https://github.com/xpepermint/rawmodeljs/issues/27.
