### ISSUE TITLE
new API

### ISSUE THREAD

**Issue by xpepermint** [xpepermint/rawmodeljs#7]
Ref: https://github.com/xpepermint/objectschemajs/issues/5

**Comment by xpepermint** [comment]
Upgrading [objectschema.js](https://github.com/xpepermint/objectschemajs) to `v4`. Ref: https://github.com/xpepermint/objectschemajs/issues/5

**Comment by smolinari** [comment]
Hey, 

I noticed the code here has no version tagging or releases. Where could someone find the code to older versions, if someone wanted to?

Scott

**Comment by xpepermint** [comment]
True. Until now the focus was on finding the right syntax, integration with GraphQL, Vue etc. I'll add tagging if that's what you're proposing.

**Comment by xpepermint** [comment]
New version is now in beta: [Branch v4](https://github.com/xpepermint/contextablejs/tree/v4)

**Comment by smolinari** [comment]
Hey Kristijan,

Your link is broken. 😄 

Scott

**Comment by xpepermint** [comment]
Things are changing quickly, yeah :). The new API is now in master. Closing ...
